name: Build MySQL Proxy

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * 2" # 2pm Patch Tuesday

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mysql-proxy-build:
    name: "Build"
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: benzine-framework/action-setup-docker@main
        with:
          ghcr_user: ${{ vars.SERVICE_ACCOUNT_USERNAME }}
          ghcr_token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}

      - name: "Setup: Checkout Source"
        uses: actions/checkout@v4

      - name: "Build: Build & Push Image"
        uses: docker/build-push-action@v5
        with:
          target: mysql-proxy
          platforms: ${{ !env.ACT && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          pull: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
          cache-from: ${{ !env.ACT && 'type=gha' || '' }}
          cache-to: ${{ !env.ACT && 'type=gha,mode=max' || '' }}
          build-contexts: |
            marshall:version=docker-image://ghcr.io/benzine-framework/marshall:focal
